# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gini_impurity_C <- function(left, right) {
    .Call(`_myds_gini_impurity_C`, left, right)
}

best_split_C <- function(X, y) {
    .Call(`_myds_best_split_C`, X, y)
}

rcpp_hello_world <- function() {
    .Call(`_myds_rcpp_hello_world`)
}

